//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMCMSv2Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtlfa
    {
        public string id { get; set; }
        public string totfa_id { get; set; }
        public string d1 { get; set; }
        public string d2 { get; set; }
        public string d3 { get; set; }
        public string d4 { get; set; }
        public string d5 { get; set; }
        public string d6 { get; set; }
        public string d7 { get; set; }
        public string d8 { get; set; }
        public string d9 { get; set; }
        public string d10 { get; set; }
        public string d11 { get; set; }
        public string d12 { get; set; }
        public string d13 { get; set; }
        public string d14 { get; set; }
        public string d15 { get; set; }
        public string d16 { get; set; }
        public string d17 { get; set; }
        public string d18 { get; set; }
        public string d19 { get; set; }
        public string d20 { get; set; }
        public string d21 { get; set; }
        public string d22 { get; set; }
        public string d23 { get; set; }
        public string d24 { get; set; }
        public string d25 { get; set; }
        public string d26 { get; set; }
        public string d27 { get; set; }
        public string d28 { get; set; }
        public string d29 { get; set; }
        public string d30 { get; set; }
        public string d31 { get; set; }
        public string d32 { get; set; }
        public string d33 { get; set; }
        public string d34 { get; set; }
        public string d35 { get; set; }
        public string d36 { get; set; }
        public string d37 { get; set; }
        public string d38 { get; set; }
        public string d39 { get; set; }
        public string d40 { get; set; }
        public string d41 { get; set; }
        public string d42 { get; set; }
        public string d43 { get; set; }
        public string d44 { get; set; }
        public string d45 { get; set; }
        public string d46 { get; set; }
        public string d47 { get; set; }
        public string d48 { get; set; }
        public string d49 { get; set; }
    }
}
