//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMCMSv2Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratoryPatient
    {
        public string id { get; set; }
        public string patient_id { get; set; }
        public string employee_id { get; set; }
        public Nullable<System.DateTime> laboratory_date { get; set; }
        public Nullable<System.DateTime> clinic_date { get; set; }
        public Nullable<System.DateTime> apply_date { get; set; }
        public Nullable<System.DateTime> report_date { get; set; }
        public string sno { get; set; }
        public string title { get; set; }
        public string lab_clinic_name { get; set; }
        public Nullable<bool> bolisDone { get; set; }
        public string comment { get; set; }
    }
}
