//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMCMSv2Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laboratoryPatientDetail
    {
        public string id { get; set; }
        public string laboratoryPatient_id { get; set; }
        public string laboratoryItem_id { get; set; }
        public string data { get; set; }
        public string result { get; set; }
        public string unit { get; set; }
        public string standard { get; set; }
        public Nullable<int> intSeq { get; set; }
        public Nullable<bool> bolisDone { get; set; }
        public string drugMemo { get; set; }
    }
}
