//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZMCMSv2Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class totfa
    {
        public string id { get; set; }
        public string t1 { get; set; }
        public string t2 { get; set; }
        public string t3 { get; set; }
        public string t4 { get; set; }
        public string t5 { get; set; }
        public string t6 { get; set; }
        public string t7 { get; set; }
        public string t8 { get; set; }
        public string t9 { get; set; }
        public string t10 { get; set; }
        public string t11 { get; set; }
        public string t12 { get; set; }
        public string t13 { get; set; }
        public string t14 { get; set; }
        public string t15 { get; set; }
        public string t16 { get; set; }
        public string t17 { get; set; }
        public string t18 { get; set; }
        public string t19 { get; set; }
        public string t20 { get; set; }
        public string t21 { get; set; }
        public string t22 { get; set; }
        public string t23 { get; set; }
        public string t24 { get; set; }
        public string t25 { get; set; }
        public string t26 { get; set; }
        public string t27 { get; set; }
        public string t28 { get; set; }
        public string t29 { get; set; }
        public string t30 { get; set; }
        public string t31 { get; set; }
        public string t32 { get; set; }
        public string t33 { get; set; }
        public string t34 { get; set; }
        public string t35 { get; set; }
        public string t36 { get; set; }
        public string t37 { get; set; }
        public string t38 { get; set; }
        public string t39 { get; set; }
        public string t40 { get; set; }
    }
}
